version: 2
jobs:
  build:
    machine: true
    working_directory: ~/npm_lazy
    environment:
      PACKAGE: process
      node: node:4.8.1

    steps:
      - checkout

      - run:
          name: Build test image
          command: docker build --rm=false -t test .

      - run:
          name: Pull Node image
          command: docker pull $node

      - run:
          name: Basic options test
          command: |
            docker run -d \
              --name basic \
              test \
                --port=80 --external-url=http://basic

            docker run \
              --link basic \
              -e npm_config_registry=http://basic \
              $node \
                npm install --verbose $PACKAGE

      - run:
          name: Environment options test
          command: |
            docker run -d --name env \
              -e NPM_LAZY_PORT=80 \
              -e NPM_LAZY_EXTERNAL_URL=http://env \
              test

            docker run --link env \
              -e npm_config_registry=http:/env \
              $node \
                npm install --verbose $PACKAGE
